services:
  redis:
    image: redis:7

    container_name: redis-dev

    ports:
      - "6379:6379"

    networks:
      - backend-network

    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:7

    container_name: mongo-dev

    ports:
      - "27017:27017"

    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

    networks:
      - backend-network

    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data:

networks:
  backend-network:
